name: release

on:
  push:
    tags:
      - '*'
jobs:
    build:
        # This job will run on ubuntu virtual machine
        runs-on: ubuntu-latest
        steps:
            # Setup Java environment in order to build the Android app.
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "11"

            # Setup the flutter environment.
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'master'

            # Fetch sub modules
            - run: git submodule update --init --recursive

            # Get flutter dependencies.
            - run: flutter pub get

            # Build independent apk.
            - name: Build
              run: flutter build apk

            # Upload generated apk to the artifacts.
            - uses: actions/upload-artifact@v2
              with:
                  name: release-apk
                  path: build/app/outputs/flutter-apk/denonceur.apk

            - uses: actions/upload-artifact@v2
              with:
                  name: release-checksum
                  path: build/app/outputs/flutter-apk/sha256sum

            # Create a Github release
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "build/app/outputs/flutter-apk/denonceur.apk"
                  token: ${{ secrets.GITHUB_TOKEN }}
